package fr.utbm.formation.entity;
// Generated 1 avr. 2016 18:23:30 by Hibernate Tools 4.3.1



/**
 * Client generated by hbm2java
 */
public class Client  implements java.io.Serializable {


     private int id;
     private char lastname;
     private char fisrtname;
     private char address;
     private char phone;
     private Character email;
     private int courseSessionId;

    public Client() {
        //-----
    }

	
    public Client(int id, char lastname, char fisrtname, char address, char phone, int courseSessionId) {
        this.id = id;
        this.lastname = lastname;
        this.fisrtname = fisrtname;
        this.address = address;
        this.phone = phone;
        this.courseSessionId = courseSessionId;
    }
    public Client(int id, char lastname, char fisrtname, char address, char phone, Character email, int courseSessionId) {
       this.id = id;
       this.lastname = lastname;
       this.fisrtname = fisrtname;
       this.address = address;
       this.phone = phone;
       this.email = email;
       this.courseSessionId = courseSessionId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public char getLastname() {
        return this.lastname;
    }
    
    public void setLastname(char lastname) {
        this.lastname = lastname;
    }
    public char getFisrtname() {
        return this.fisrtname;
    }
    
    public void setFisrtname(char fisrtname) {
        this.fisrtname = fisrtname;
    }
    public char getAddress() {
        return this.address;
    }
    
    public void setAddress(char address) {
        this.address = address;
    }
    public char getPhone() {
        return this.phone;
    }
    
    public void setPhone(char phone) {
        this.phone = phone;
    }
    public Character getEmail() {
        return this.email;
    }
    
    public void setEmail(Character email) {
        this.email = email;
    }
    public int getCourseSessionId() {
        return this.courseSessionId;
    }
    
    public void setCourseSessionId(int courseSessionId) {
        this.courseSessionId = courseSessionId;
    }




}


