package fr.utbm.formation.entity;
// Generated 1 avr. 2016 18:23:30 by Hibernate Tools 4.3.1



/**
 * Client generated by hbm2java
 */
public class Client  implements java.io.Serializable {


     private int id;
     private String lastname;
     private String fisrtname;
     private String address;
     private String phone;
     private String email;
     private CourseSession courseSession;

    public Client() {
        //-----
        //58796161416
    }

	
    public Client(int id, String lastname, String fisrtname, String address, String phone, CourseSession cs) {
        this.id = id;
        this.lastname = lastname;
        this.fisrtname = fisrtname;
        this.address = address;
        this.phone = phone;
        this.courseSession = cs;
    }
    public Client(int id, String lastname, String fisrtname, String address, String phone, String email, CourseSession cs) {
       this.id = id;
       this.lastname = lastname;
       this.fisrtname = fisrtname;
       this.address = address;
       this.phone = phone;
       this.email = email;
       this.courseSession = cs;
    }
   
    public Client(int id, String lastname, String fisrtname, String address, String phone, String email) {
       this.id = id;
       this.lastname = lastname;
       this.fisrtname = fisrtname;
       this.address = address;
       this.phone = phone;
       this.email = email;
    }
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public String getFisrtname() {
        return this.fisrtname;
    }
    
    public void setFisrtname(String fisrtname) {
        this.fisrtname = fisrtname;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public CourseSession getCourseSession() {
        return this.courseSession;
    }
    
    public void setCourseSession(CourseSession cs) {
        this.courseSession = cs;
    }

}


