package fr.utbm.formation.entity;
// Generated 1 avr. 2016 18:23:30 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * CourseSession generated by hbm2java
 */
public class CourseSession  implements java.io.Serializable {


     private int id;
     private Date startDate;
     private Date endDate;
     private char courseCode;
     private int locationId;

    public CourseSession() {
    }

    public CourseSession(int id, Date startDate, Date endDate, char courseCode, int locationId) {
       this.id = id;
       this.startDate = startDate;
       this.endDate = endDate;
       this.courseCode = courseCode;
       this.locationId = locationId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public char getCourseCode() {
        return this.courseCode;
    }
    
    public void setCourseCode(char courseCode) {
        this.courseCode = courseCode;
    }
    public int getLocationId() {
        return this.locationId;
    }
    
    public void setLocationId(int locationId) {
        this.locationId = locationId;
    }




}


