package fr.utbm.formation.entity;
// Generated 1 avr. 2016 18:23:30 by Hibernate Tools 4.3.1



/**
 * Course generated by hbm2java
 */
public class Course  implements java.io.Serializable {


     private char code;
     private char title;

    public Course() {
    }

    public Course(char code, char title) {
       this.code = code;
       this.title = title;
    }
   
    public char getCode() {
        return this.code;
    }
    
    public void setCode(char code) {
        this.code = code;
    }
    public char getTitle() {
        return this.title;
    }
    
    public void setTitle(char title) {
        this.title = title;
    }




}


