package fr.utbm.formation.entity;
// Generated 1 avr. 2016 18:23:30 by Hibernate Tools 4.3.1



/**
 * Course generated by hbm2java
 */
public class Course  implements java.io.Serializable {


     private int code;
     private String title;

    public Course() {
    }

    public Course(int code, String title) {
       this.code = code;
       this.title = title;
    }
   
    public int getCode() {
        return this.code;
    }
    
    public void setCode(int code) {
        this.code = code;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }




}


