package fr.utbm.formation.entity;
// Generated 1 avr. 2016 18:23:30 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * CourseSession generated by hbm2java
 */
public class CourseSession  implements java.io.Serializable {

     private int id;
     private Date startDate;
     private Date endDate;
     private Course course;
     private Location location;

    public CourseSession() {
    }

    public CourseSession(int id, Date startDate, Date endDate, Course c, Location l) {
       this.id = id;
       this.startDate = startDate;
       this.endDate = endDate;
       this.course = c;
       this.location = l;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public Course getCourse() {
        return this.course;
    }
    
    public void setCourse(Course c) {
        this.course = c;
    }
    public Location getLocation() {
        return this.location;
    }
    
    public void setLocation(Location l) {
        this.location = l;
    }




}


