package fr.utbm.formation.entity;
// Generated 1 avr. 2016 18:23:30 by Hibernate Tools 4.3.1



/**
 * Location generated by hbm2java
 */
public class Location  implements java.io.Serializable {


     private int id;
     private char city;

    public Location() {
    }

    public Location(int id, char city) {
       this.id = id;
       this.city = city;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public char getCity() {
        return this.city;
    }
    
    public void setCity(char city) {
        this.city = city;
    }




}


